# Generated by Django 2.2.4 on 2019-09-01 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('desc', models.TextField(max_length=1024)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event_start', models.DateTimeField()),
                ('event_end', models.DateTimeField()),
                ('banner_url', models.URLField()),
                ('card_image_url', models.URLField()),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='events.Catagory')),
                ('organizer_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_organizer_1', to='events.Organizer')),
                ('organizer_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_organizer_2', to='events.Organizer')),
            ],
        ),
    ]
