# Generated by Django 2.2.4 on 2019-09-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='desc',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='catagory',
            name='thumb',
            field=models.URLField(null=True),
        ),
    ]
