# Generated by Django 2.2.4 on 2019-09-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190909_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='card_image_url',
            new_name='reg_link',
        ),
    ]
